#####################################
# Site / Theme Configuration
#####################################
# Menu
menu:
  Home: /
  CV: cv
  Portfolio: portfolio
  Ethos: ethos
  About: about
rss: /atom.xml

# Sidebar
sidebar: right
widgets:
  #- search
- profile
- social
- recent_posts
  #- category
  #- tag
  #- tagcloud
  #- archive

# Profile Picture
profile: profile.jpg

# Social Links
# Key is Font Awesome icon name, value is target link
social:
  LinkedIn: https://www.linkedin.com/in/michaelthanh/
  Github: https://github.com/mvxt
  Youtube: https://www.youtube.com/channel/UCD9Vpco6dO5GfYOSmipwlvg
  Medium: https://medium.com/@michael.thanh

# HTML Page Metadata
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
favicon: favicon.ico
google_site_verification:

