#####################################
# Site / Theme Configuration
#####################################
# Menu
menu:
  Home: /
  CV: cv
  Portfolio: portfolio
  Ethos: ethos
  About: about
rss: /atom.xml

# Sidebar
sidebar: right
widgets:
- profile
- social
- recent_posts
- category
- tagcloud
- archive

# Widget Options
archive_type: 'monthly'
show_count: true

# Profile Picture
profile: profile.jpg

# Social Links
# Key is Font Awesome icon name, value is target link
social:
  LinkedIn: https://www.linkedin.com/in/michaelthanh/
  Github: https://github.com/mvxt
  Youtube: https://www.youtube.com/channel/UCD9Vpco6dO5GfYOSmipwlvg
  Medium: https://medium.com/@michael.thanh

# Search
search:
  insight: true # Install `hexo-generator-json-content` before using Insight Search

# HTML Page Metadata
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
favicon: favicon.ico
google_site_verification:

