#####################################
# Site / Theme Configuration
#####################################
# Menu
menu:
  Home: /
  CV: cv
  Ethos: ethos
rss: /atom.xml

# Sidebar
widgets:
  #- profile
  #- social
  #- recent_posts
  #- category
  #- archive

# Widget Options
archive_type: 'monthly'
show_count: true

# Profile Picture - place inside /source/img
# Only shows up if profile enabled in widgets
profile: /img/profile.jpg

# Social Links
# Key is Font Awesome icon name, value is target link
# See Font Awesome icons at: https://fontawesome.com/icons?d=gallery
social:
  Twitch: https://www.twitch.tv/vinnythen00b
  Medium-M: https://medium.com/@michael.thanh
  Github: https://github.com/mvxt
  LinkedIn-In: https://www.linkedin.com/in/michaelthanh
  Twitter: https://twitter.com/vinnythen00b
  Instagram: https://www.instagram.com/vinnythen00b

# Search
search:
  insight: false # Install `hexo-generator-json-content` before using Insight Search

# HTML Page Metadata
# Google Webmaster tools verification setting
# See: https://www.google.com/webmasters/
favicon: favicon.ico
google_site_verification: FHK_lhsTlcLbPDI5IkA4bjEvJ2R6JzO66YFIP83rNwg

