home: Home
archives: Archives
about: About
categories: Categories
search: Search
tags: Tags
tagcloud: Tag Cloud
tweets: Tweets
prev: Prev
next: Next
comment: Comments
archive_a: Archives
archive_b: "Archives: %s"
page: Page %d
recent_posts: Recent Posts
newer: Newer
older: Older
share: Share
theme_by: Modified from theme by
rss_feed: RSS Feed
category: Category
tag: Tag
connect: 'Connect With Us'
post_total_count_one: There is %d post.
post_total_count: There are %d posts.
read_more: Continue Reading →
contents: Contents
rights_reserved: All Rights Reserved
site_built: Site built with
none: None
insight:
    hint: 'Type something...'
    posts: 'Posts'
    pages: 'Pages'
    categories: 'Categories'
    tags: 'Tags'
    untitled: '(Untitled)'
